pipeline{
    agent any

    stages {
        stage ('Compile Stage') {
            steps {
                dir('automationSolution') {
                    withMaven(maven: 'Maven_3.9.0') {
                        sh 'mvn clean install'
                    }
                }
            }
        }

    stage ('Test Stage') {
            steps {
                 dir('automationSolution') {
                     withMaven(maven: 'Maven_3.9.0') {
                         sh 'mvn test -Dtest="AddProductsToCarAndCheckoutRunner"'
                     }
                 }
            }
        }

        stage ('Cucumber Reports') {
            steps {
                cucumber buildStatus: "UNSTABLE",
                    fileIncludePattern: "**/cucumber.json",
                    jsonReportDirectory: 'target'
            }
        }
    }
}