pipeline{
    agent any

    stages {
        stage ('Compile Stage') {
            steps {
                dir('automationSolution') {
                  sh "pwd"
                }
                withMaven(maven: 'Maven_3.9.0') {
                    sh 'cd automationSolution mvn clean install'
                }
            }
        }

    stage ('Test Stage') {
            steps {
                dir('automationSolution') {
                  sh "pwd"
                }
                withMaven(maven: 'maven_3_5_0') {
                    sh 'mvn test -e -Dgroups=categories.dbd -Dtest=automated_test.option_two.AddProductsToCarAndCheckoutRunner'
                }
            }
        }

        stage ('Cucumber Reports') {
            steps {
                cucumber buildStatus: "UNSTABLE",
                    fileIncludePattern: "**/cucumber.json",
                    jsonReportDirectory: 'target'
            }
        }
    }
}